"""slug nullable changed

Revision ID: 6c53c9c0d36b
Revises: d81bfbf3de8a
Create Date: 2025-04-12 15:50:28.604209

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import text  # <-- Make sure this is imported

# revision identifiers, used by Alembic.
revision = "6c53c9c0d36b"
down_revision = "d81bfbf3de8a"
branch_labels = None
depends_on = None


def upgrade():
    # Set slug values for existing posts based on title or id
    conn = op.get_bind()
    conn.execute(
        text(
            """
        UPDATE posts
        SET slug = lower(regexp_replace(title, '[^a-zA-Z0-9]+', '-', 'g'))
        WHERE slug IS NULL
    """
        )
    )

    # Now make the slug column NOT NULL
    with op.batch_alter_table("posts") as batch_op:
        batch_op.alter_column("slug", nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("posts", schema=None) as batch_op:
        batch_op.alter_column(
            "slug", existing_type=sa.VARCHAR(length=255), nullable=True
        )

    # ### end Alembic commands ###
