"""Update foreign key column names ot camelCase

Revision ID: a5d511ce0dd9
Revises: 54f1673cb421
Create Date: 2025-04-08 14:46:49.899288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5d511ce0dd9'
down_revision = '54f1673cb421'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('userId', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('postId', sa.Integer(), nullable=False))
        batch_op.drop_constraint('comments_post_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('comments_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'posts', ['postId'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['userId'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('post_id')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('userId', sa.Integer(), nullable=False))
        batch_op.drop_constraint('posts_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['userId'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('posts_user_id_fkey', 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('userId')

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('comments_user_id_fkey', 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('comments_post_id_fkey', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('postId')
        batch_op.drop_column('userId')

    # ### end Alembic commands ###
